# Generated by Django 2.0.1 on 2018-03-28 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
